name = "DualDecomposition"
uuid = "d0e446f1-e135-48f1-a6ea-e9a6190f2a7a"
authors = ["Kibaek Kim <kimk@anl.gov>"]
version = "0.1.0"

[deps]
BundleMethod = "e8a6717a-069f-43d5-9ac2-a49b1ec5be7b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BundleMethod = "0.1.3"
JuMP = "0.21.3"
MPI = "0.15.0"
julia = "1"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "GLPK"]
