name = "DualDecomposition"
uuid = "d0e446f1-e135-48f1-a6ea-e9a6190f2a7a"
authors = ["Kibaek Kim <kimk@anl.gov>"]
version = "0.3.0"

[deps]
BundleMethod = "e8a6717a-069f-43d5-9ac2-a49b1ec5be7b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BundleMethod = "0.3.2"
JuMP = "0.21.8"
MPI = "0.16.1"
julia = "1"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "GLPK", "Random"]
